[package]
name = "gold"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "4.0", features = ["derive"] }
dotenv = "0.15"
glob = "0.3"
rust-s3 = "0.35.1"
tokio = { version = "1.0", features = ["full"] }

